// Code generated by mockery v2.9.4. DO NOT EDIT.

package transaction

import (
	transaction "github.com/nogurenn/cph-wallet/transaction"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: username
func (_m *Service) CreateAccount(username string) error {
	ret := _m.Called(username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccounts provides a mock function with given fields:
func (_m *Service) GetAccounts() ([]transaction.Account, error) {
	ret := _m.Called()

	var r0 []transaction.Account
	if rf, ok := ret.Get(0).(func() []transaction.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
